from functions import toggles, state

key_with_toggle = {
    'f1': [toggles.toggle_f1, state.pressed_f1],
    'f2': [toggles.toggle_f2, state.pressed_f2],
    'f3': [toggles.toggle_f3, state.pressed_f3],
    'f4': [toggles.toggle_f4, state.pressed_f4],
    'f5': [toggles.toggle_f5, state.pressed_f5],
    'f6': [toggles.toggle_f6, state.pressed_f6],
    'f7': [toggles.toggle_f7, state.pressed_f7],
    'f8': [toggles.toggle_f8, state.pressed_f8],
    'f9': [toggles.toggle_f9, state.pressed_f9],
    'f10': [toggles.toggle_f10, state.pressed_f10],
    'q': [toggles.toggle_q, state.pressed_q],
    'w': [toggles.toggle_w, state.pressed_w],
    'e': [toggles.toggle_e, state.pressed_e],
    'r': [toggles.toggle_r, state.pressed_r],
    't': [toggles.toggle_t, state.pressed_t],
    'y': [toggles.toggle_y, state.pressed_y],
    'u': [toggles.toggle_u, state.pressed_u],
    'i': [toggles.toggle_i, state.pressed_i],
    'o': [toggles.toggle_o, state.pressed_o],
    'p': [toggles.toggle_p, state.pressed_p],
    '1': [toggles.toggle_1, state.pressed_1],
    '2': [toggles.toggle_2, state.pressed_2],
    '3': [toggles.toggle_3, state.pressed_3],
    '4': [toggles.toggle_4, state.pressed_4],
    '5': [toggles.toggle_5, state.pressed_5],
    '6': [toggles.toggle_6, state.pressed_6],
    '7': [toggles.toggle_7, state.pressed_7],
    '8': [toggles.toggle_8, state.pressed_8],
    '9': [toggles.toggle_9, state.pressed_9],
    '`': [toggles.toggle_tilda, state.pressed_tilda]
}
