from functions import toggles, state, press_keys

# key_with_toggle = {
#     'f1': [toggles.toggle_f1, state.pressed_f1],
#     'f2': [toggles.toggle_f2, state.pressed_f2],
#     'f3': [toggles.toggle_f3, state.pressed_f3],
#     'f4': [toggles.toggle_f4, state.pressed_f4],
#     'f5': [toggles.toggle_f5, state.pressed_f5],
#     'f6': [toggles.toggle_f6, state.pressed_f6],
#     'f7': [toggles.toggle_f7, state.pressed_f7],
#     'f8': [toggles.toggle_f8, state.pressed_f8],
#     'f9': [toggles.toggle_f9, state.pressed_f9],
#     'f10': [toggles.toggle_f10, state.pressed_f10],
#     'q': [toggles.toggle_q, state.pressed_q],
#     'w': [toggles.toggle_w, state.pressed_w],
#     'e': [toggles.toggle_e, state.pressed_e],
#     'r': [toggles.toggle_r, state.pressed_r],
#     't': [toggles.toggle_t, state.pressed_t],
#     'y': [toggles.toggle_y, state.pressed_y],
#     'u': [toggles.toggle_u, state.pressed_u],
#     'i': [toggles.toggle_i, state.pressed_i],
#     'o': [toggles.toggle_o, state.pressed_o],
#     'p': [toggles.toggle_p, state.pressed_p],
#     '1': [toggles.toggle_1, state.pressed_1],
#     '2': [toggles.toggle_2, state.pressed_2],
#     '3': [toggles.toggle_3, state.pressed_3],
#     '4': [toggles.toggle_4, state.pressed_4],
#     '5': [toggles.toggle_5, state.pressed_5],
#     '6': [toggles.toggle_6, state.pressed_6],
#     '7': [toggles.toggle_7, state.pressed_7],
#     '8': [toggles.toggle_8, state.pressed_8],
#     '9': [toggles.toggle_9, state.pressed_9],
#     '`': [toggles.toggle_tilda, state.pressed_tilda]
# }

down = 256
up = 257

keys_num = {
    '1': 49,
    '2': 50,
    '3': 51,
    '4': 52,
    '5': 53,
    '6': 54,
    '7': 55,
    '8': 56,
    '9': 57,
    'f1': 112,
    'f2': 113,
    'f3': 114,
    'f4': 115,
    'f5': 116,
    'f6': 117,
    'f7': 118,
    'f8': 119,
    'f9': 120,
    'f10': 121,
    '`': 192,
    'q': 81,
    'w': 87,
    'e': 69,
    'r': 82,
    't': 84,
    'y': 89,
    'u': 85,
    'i': 73,
    'o': 79,
    'p': 80
}

# key_with_press = {
#     'f1': [press_keys.press_f1, state.pressed_f1],
#     'f2': [press_keys.press_f2, state.pressed_f2],
#     'f3': [press_keys.press_f3, state.pressed_f3],
#     'f4': [press_keys.press_f4, state.pressed_f4],
#     'f5': [press_keys.press_f5, state.pressed_f5],
#     'f6': [press_keys.press_f6, state.pressed_f6],
#     'f7': [press_keys.press_f7, state.pressed_f7],
#     'f8': [press_keys.press_f8, state.pressed_f8],
#     'f9': [press_keys.press_f9, state.pressed_f9],
#     'f10': [press_keys.press_f10, state.pressed_f10],
#     'q': [press_keys.press_q, state.pressed_q],
#     'w': [press_keys.press_w, state.pressed_w],
#     'e': [press_keys.press_e, state.pressed_e],
#     'r': [press_keys.press_r, state.pressed_r],
#     't': [press_keys.press_t, state.pressed_t],
#     'y': [press_keys.press_y, state.pressed_y],
#     'u': [press_keys.press_u, state.pressed_u],
#     'i': [press_keys.press_i, state.pressed_i],
#     'o': [press_keys.press_o, state.pressed_o],
#     'p': [press_keys.press_p, state.pressed_p],
#     '1': [press_keys.press_1, state.pressed_1],
#     '2': [press_keys.press_2, state.pressed_2],
#     '3': [press_keys.press_3, state.pressed_3],
#     '4': [toggles.toggle_4, state.pressed_4],
#     '5': [toggles.toggle_5, state.pressed_5],
#     '6': [toggles.toggle_6, state.pressed_6],
#     '7': [toggles.toggle_7, state.pressed_7],
#     '8': [toggles.toggle_8, state.pressed_8],
#     '9': [toggles.toggle_9, state.pressed_9],
#     '`': [toggles.toggle_tilda, state.pressed_tilda]
# }